### ISSUE TITLE
Question: theme-company cant access images

### ISSUE THREAD

**Issue by PedroMSantosD** [Icinga/icingaweb2-theme-company#10]
Hi,
I'm running icingaweb2-2.11.4-1.el7.noarch and have just started playing with this module. I was wondering if you could help provide where the images folder is resolved to on the server?

When I load icingweb with the company default theme enabled, the CSS file public/css/themes/default.less seems to be read ok, as I'm able to change the variable 
```
@icinga-blue: #2196F3;
```
and the background gets fully changed, plus the front end application tries to load the images specified on the file. Yet, neither of the images gets loaded (404 not found on dev tools).

I was wondering if you can tell which one should be the path to the folder (either absolute or relative for the module path: img/<filename>.<svg|jpg>) for icingaweb2 application to be able to serve them.

the relatives url described on the [repo](https://github.com/Icinga/icingaweb2-theme-company/blob/master/public/css/themes/default.less#LL23C3-L23C58) yield a 404, and I'm not able to 'guess' which path should be specified (unless I use a remote URL...which should not be)

![image](https://github.com/Icinga/icingaweb2-theme-company/assets/17711131/8e4f4af9-5ce8-46ed-8f77-8d39324e46f7)

Thanks in advance

**Comment by nilmerg** [comment]
Hi,

the URL is resolved relative to url of the CSS file, in your case this is `icinga2.?.com/css`. `../img/...` then resolves to `icinga2.?.com/img/...`.

The path on the filesystem then is relative to the module installation folder `img/company` points to `/usr/share/icingaweb2/modules/company/public/img`.

I hope that answers the question. Though, next time please ask such in the [forum](https://community.icinga.com/).

**Comment by PedroMSantosD** [comment]
Thanks @nilmerg .
