### ISSUE TITLE
Getting weird error

### ISSUE THREAD

**Issue by realmayus** [Icinga/icingaweb2-theme-company#4]
Hi! I'm getting this error when cloning this repo into the modules folder and then enabling it:

Fatal error: Uncaught Icinga\Exception\ProgrammingError: Cannot find renderer "ConfigHealthItemRenderer" for navigation item "Activity log" in /usr/share/php/Icinga/Web/Navigation/NavigationItem.php:724 Stack trace: #0 /usr/share/php/Icinga/Web/Navigation/NavigationItem.php(748): Icinga\Web\Navigation\NavigationItem->createRenderer('ConfigHealthIte...') #1 /usr/share/php/Icinga/Web/Navigation/NavigationItem.php(608): Icinga\Web\Navigation\NavigationItem->setRenderer('ConfigHealthIte...') #2 /usr/share/php/Icinga/Web/Navigation/NavigationItem.php(145): Icinga\Web\Navigation\NavigationItem->setProperties(Array) #3 /usr/share/php/Icinga/Web/Navigation/Navigation.php(139): Icinga\Web\Navigation\NavigationItem->__construct('Activity log', Array) #4 /usr/share/php/Icinga/Web/Navigation/Navigation.php(205): Icinga\Web\Navigation\Navigation->createItem('Activity log', Array) #5 /usr/share/php/Icinga/Web/Navigation/Navigation.php(568): Icinga\Web\Navigation\Navigation->addItem('Activity log', Array) #6 /usr/share/php/Icinga/Web/Na in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332

This is the command i used to clone the repo:
```bash
sudo git clone https://github.com/Icinga/icingaweb2-module-director.git /usr/share/icingaweb2/modules/ourtheme
```

**Comment by realmayus** [comment]
Turns out that I have to clone the repo into a folder called 'company'.

**Comment by lazyfrosch** [comment]
> Turns out that I have to clone the repo into a folder called 'company'.

As stated in README :wink:
