### ISSUE TITLE
Either not compatible or not as advertised

### ISSUE THREAD

**Issue by realmayus** [Icinga/icingaweb2-theme-company#6]
When I choose the theme, it just changes the login-screen background. Is it possible to get the exact same theme you show in the screenshot?

**Comment by lazyfrosch** [comment]
Uhm it should work in all versions...

But there are two settings:
* User setting in `Username -> My Account`
* Global setting in `Configuration -> Application`
* There is also a global setting to force the theme

Also you might want to reload the tab after changing themes.

Please describe your environment when you continue to have problems...

**Comment by realmayus** [comment]
Turns out that I have Icinga v.2.4.1 installed (that's what the web interface says)
Because I am running icinga on a Raspberry Pi 3 B+, I can't get any newer icinga packages, 
`apt-cache policy icinga2` just gives the following output:
```
icinga2:
  Installed: 2.6.0-2
  Candidate: 2.6.0-2
  Version table:
 *** 2.6.0-2 500
        500 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
        100 /var/lib/dpkg/status
```

Do you have any fix for this/how can I update Icinga when I'm on a Raspberry Pi?

Thank you very much in advance.

**Comment by lazyfrosch** [comment]
True, the theme is built for Icinga Web 2 >= 2.5.

Packages for Raspbian will be published soon, please follow: https://github.com/Icinga/icinga-packaging/issues/20

**Comment by realmayus** [comment]
Thanks!
